version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: aHR0cC1mb3ItYXM2NGEtc3VmZmljaWVuY3ktZXhhbQ==
      
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: aHR0cC1mb3ItYXM2NGEtc3VmZmljaWVuY3ktZXhhbQ==

volumes:
  mongodb_data: